version: '3.1'

services:
  db:
    image: postgres:17
    container_name: devtraining-db
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=devtraining